"""Add is_deleted column to Task

Revision ID: 2ceedffb69c2
Revises: 
Create Date: 2024-07-11 02:29:50.597824

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ceedffb69c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=True))

    # 既存のレコードにデフォルト値を設定
    op.execute("UPDATE task SET is_deleted = False")

    # その後、カラムを非NULLに変更
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column("is_deleted", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
