"""Remove is_deleted column from Task

Revision ID: 482e159c010e
Revises: 2ceedffb69c2
Create Date: 2024-07-11 11:52:20.397157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482e159c010e'
down_revision = '2ceedffb69c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
